# Generated by Django 4.2.2 on 2023-06-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
